# Generated by Django 5.2.10 on 2026-01-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
